CREATE DATABASE IF NOT EXISTS shortify;

CREATE TABLE IF NOT EXISTS links (
	id INT AUTO_INCREMENT PRIMARY KEY,
	url CHAR(200) NOT NULL,
	cutback CHAR(30) NOT NULL,
	timestamp TIMESTAMP
) ENGINE = InnoDB;
